# Generated by Django 5.2.7 on 2026-03-10 10:02

import clinica.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9, unique=True, validators=[clinica.models.validar_dni])),
                ('telefono', models.CharField(max_length=9, validators=[clinica.models.validar_telefono])),
                ('edad', models.IntegerField(validators=[clinica.models.validar_mayoria_edad])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Exotico', 'Exótico')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[clinica.models.validar_peso_positivo])),
                ('fecha_nacimiento', models.DateField(validators=[clinica.models.validar_fecha_pasada])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clinica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(validators=[clinica.models.validar_fecha_futura])),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(validators=[clinica.models.validar_longitud_motivo])),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.mascota')),
            ],
        ),
    ]
